- name: Set Ip loobpack
  hosts: all
  gather_facts: no
  tasks:
    - name: Set loopdack ipv4 address
        name: loobpack {{ item.name }}
        ipv4: 10.0.{{ item.number}}.1/24
      with_itmes:
        - { name: "0", number: 0}
        - { name: "1", number: 1}
        - { name: "2", number: 2}
    - name: Show ip
      ios_command:
        command:
          - show ip int brief
      register: show_ip
    - debug: var=show_ip.stdout_lines
